$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code:
  local_path: src
command: >-
  python main.py 
  --cuda 
  --epochs ${{inputs.epochs}}
  --model ${{inputs.model}}
  --lr ${{inputs.lr}}
  --data ${{inputs.corpus}}
  --save ${{inputs.save}}
inputs:
  epochs: 1
  model: Transformer
  lr: 5
  save: outputs/model.pt
  corpus:
    dataset:
      local_path: data
    mode: download
<<<<<<< HEAD:cli/jobs/train/pytorch/word-language-model/job.yml
environment: azureml:AzureML-pytorch-1.9-ubuntu18.04-py37-cuda11-gpu:3
compute:
  target: azureml:customer-demo
=======
environment: azureml:AzureML-pytorch-1.9-ubuntu18.04-py37-cuda11-gpu:6
compute: azureml:gpu-cluster
display_name: pytorch-word-language-model-example
>>>>>>> 4d433622b6207d2f7df216b5fdcc2dc42cb01529:cli/jobs/single-step/pytorch/word-language-model/job.yml
experiment_name: pytorch-word-language-model-example
description: Train a multi-layer RNN (Elman, GRU, or LSTM) on a language modeling task with PyTorch.
